# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  clean:
    desc: Clean the project
    cmds:
      - rm -f ghrp
  build:
    desc: Build the project
    deps:
      - clean
    cmds:
      - rm -f ghrp
      - go build -o ghrp main.go
